- debug:
    msg: "Backup repository cloned to {{ backup_destination }}"

- name: Register backup destination
  stat:
    path: "{{ backup_destination }}"
  register: backup_destination_exists

- name: Clone backup repository
  remote_user: "{{ backup_user }}"
  git:
    repo: "{{ backup_repo_url }}"
    dest: "{{ backup_destination }}"
    version: "{{ backup_repo_branch }}"
    bare: true
  when: not backup_destination_exists.stat.exists

- name: inport task for making sure there is aliases file sourced
  import_tasks: aliases_file.yml
