- name: import task for cloning repo
  import_tasks: clone_repo.yml

- name: inport task for making sure there is aliases file sourced
  import_tasks: aliases_file.yml

- name: Set fact config command as variable
  ansible.builtin.set_fact:
    config_command: "/usr/bin/git --git-dir={{ backup_destination }}/ --work-tree=$HOME"

- name: debug config command
  debug:
    var: config_command

- name: Add command to alias file
  ansible.builtin.lineinfile:
    path: "~//{{ aliases_file }}"
    line: "alias config='{{ config_command }}'"
    create: yes
    mode: '0644'

- name: Get stdin of config show untracked files
  shell: "{{ config_command }} config --local status.showUntrackedFiles"
  changed_when: false
  register: untracked_files

- debug:
    var: untracked_files.stdout

- name: set no to showUntrackedFiles if stdout is not 'no'
  shell: "{{ config_command }} config --local status.showUntrackedFiles no"
  when: untracked_files.stdout != 'no'


- name: Add cron record to pull changes
  cron:
    name: "backup_pull"
    state: present
    user: "{{ backup_user }}"
    job: "{{ config_command }} pull"
    minute: "0"

- name: Add master cron record to commit changes
  cron:
    name: "backup_master_commit"
    state: present
    user: "{{ backup_user }}"
    job: "{{ config_command }} commit -am \"Automated backup $(date)\""
    minute: "0"
  when: backup_role == "master"

- name: Add master cron record to push changes
  cron:
    name: "backup_master_push"
    state: present
    user: "{{ backup_user }}"
    job: "{{ config_command }} push"
    minute: "0"
  when: backup_role == "master"
